import{c as h,s as P,a as p,b as y,o as _,d as j,h as D}from"./assets/exerciseHandlers-85059fa2.js";import{h as W}from"./assets/vendor-478dae0d.js";const v=document.querySelector(".scrollup-btn"),z=function(){window.scrollY<300?v.classList.add("visually-hidden"):v.classList.remove("visually-hidden")};window.addEventListener("scroll",z);v.addEventListener("click",N);function N(){window.scrollTo({top:0,behavior:"smooth"})}const L=document.querySelector(".js-header-menu"),I=document.querySelector(".overlay"),O=getComputedStyle(document.documentElement),U=parseInt(O.getPropertyValue("--breakpoint-md").trim());function Q(){document.querySelectorAll(".js-toggle-menu-btn").forEach(e=>{e.removeEventListener("click",M)})}function R(){document.querySelectorAll(".js-toggle-menu-btn").forEach(e=>{e.addEventListener("click",M)})}function M(){L.classList.toggle("open"),I.classList.toggle("open"),document.body.classList.toggle("no-scroll"),document.documentElement.style.overflow=L.classList.contains("open")?"hidden":""}function T(){window.innerWidth>=U?(L.classList.remove("open"),I.classList.remove("open"),document.body.classList.remove("no-scroll"),document.documentElement.style.overflow="",Q()):R()}const V=document.querySelector(".quote-text-wrapper"),C=document.querySelector(".filter-list"),w=document.querySelector(".pagination-section");function b(n){const e=n.results.map(t=>`
        <li class="filter-item">
          <button type="submit" class="filter-btn untreated" data-filter=${t.filter} data-name=${t.name}>
            <div class="filter-container">
              <img class="filter-img" src="${t.imgURL}" alt="${t.name}" width=335 height=225>
              <div class="filter-overlay"></div>
              <p class="filter-name">${t.name}</p>
              <p class="filter-filter">${t.filter}</p>
            </div>  
          </button>
        </li>
      `).join("");C.insertAdjacentHTML("beforeend",e)}function H(n){let e="";for(let t=1;t<=n.totalPages;t++)e+=`
      <button type="button" class="pagination-btn untreated${t===1?" active":""}" data-page=${t}>${t}</button>
    `;w.insertAdjacentHTML("beforeend",e)}function B(n){const e=`
    <p class="quote-text">${n.quote}</p>
    <p class="quote-author">${n.author}</p>
  `;V.insertAdjacentHTML("beforeend",e)}function J(n){document.querySelectorAll(".nav-btn").forEach(t=>t.classList.remove("decorated")),n.target.classList.add("decorated")}function E(n){C.innerHTML="",n&&(w.innerHTML="")}function Y(n){w.querySelectorAll(".pagination-btn").forEach(t=>t.classList.remove("active")),n.classList.add("active"),window.scrollTo(0,800)}async function S({page:n=1,limit:e=12,filter:t}){var s,r;try{return(await h.get("filters",{params:{page:n,limit:e,filter:t}})).data}catch(a){throw new Error(((r=(s=a.response)==null?void 0:s.data)==null?void 0:r.message)||a.message)}}async function G(){var n,e;try{return(await h.get("quote")).data}catch(t){throw new Error(((e=(n=t.response)==null?void 0:n.data)==null?void 0:e.message)||t.message)}}const m={filter:"Muscles",page:1,limit:null};async function X(n){if(n.target.classList.contains("nav-btn")){J(n),E(!0),m.page=1,m.filter=n.target.dataset.filter;const e=await S(m);b(e),H(e)}}async function Z(){const n=W().format("L"),e=JSON.parse(localStorage.getItem("quote-data"));if(!e||e.date!==n){const t=await G();B(t);const s={};s.date=n,s.quote=t.quote,s.author=t.author,localStorage.clear("quote-data"),localStorage.setItem("quote-data",JSON.stringify(s))}else B(e)}async function A(){const n=window.innerWidth;let e=null;if(n>1439?e=12:e=9,e!==m.limit){E(!0),m.page=1,m.limit=e;const t=await S(m);b(t),H(t)}}async function K(n){if(n.target.classList.contains("pagination-btn")){E();const e=n.target;m.page=e.dataset.page;const t=await S(m);b(t),Y(e)}}async function ee(n){var e,t;try{return(await h.post("subscription",{email:n})).data}catch(s){throw new Error(((t=(e=s.response)==null?void 0:e.data)==null?void 0:t.message)||s.message)}}const F=document.querySelector(".subscribe__form"),$=F.querySelector('[name="email"]');async function te(n){if(n.preventDefault(),!!$.value)try{const e=$.value,t=await ee(e);P(t.message),F.reset()}catch(e){p(e.message)}}async function ne({page:n=1,limit:e=12,bodypart:t,muscles:s,equipment:r,keyword:a}){var i,l;try{return(await h.get("exercises",{params:{page:n,limit:e,bodypart:t,muscles:s,equipment:r,keyword:a}})).data}catch(d){throw new Error(((l=(i=d.response)==null?void 0:i.data)==null?void 0:l.message)||d.message)}}function k(n){const e=document.getElementById("exercise-list");if(!Array.isArray(n)){console.error("Expected exercises to be an array, but received:",n);return}e.innerHTML=n.map(s=>`
        <div class="exercise-card">
            <div class="exercise-card-rating">
                <div class="exercise-card-wrapper">
                    <span class="exercise-card-workout">workout</span>
                <p class="exercise-card-ret">${Math.round(s.rating).toFixed(1)}</p>
                <svg class="exercize-icon-star" width="18" height="18">
                    <use href="${y}#icon-star"></use>
                </svg>
                </div>
                <button class="start-btn" data-id="${s._id}">
                    Start
                    <svg class="exercize-icon-arrow" width="16" height="16">
                        <use href="${y}#arrow"></use>
                    </svg>
                </button>
            </div>
            <div class="exercise-card-name">
                <svg class="exercize-icon-cross" width="24" height="24">
                    <use href="${y}#running-stick-figure-border"></use>
                </svg>
                <h3 class="exercise-card-name-title">${s.name}</h3>
            </div>
            <div class="exercise-card-info">
                <p class="exercise-card-info-cal">Burned calories: ${s.burnedCalories} / ${s.time} min </p>
                <p class="exercise-card-info-body">Body part: ${s.bodyPart}</p>
                <p class="exercise-card-info-terget">Target: ${s.target}</p>
            </div>
        </div>
    `).join(""),document.querySelectorAll(".start-btn").forEach(s=>{s.addEventListener("click",r=>{const a=r.target.dataset.id;_(a)})})}async function se({page:n,limit:e,bodypart:t,muscles:s,equipment:r,keyword:a}){j();try{const i=await ne({page:n,limit:e,bodypart:t,muscles:s,equipment:r,keyword:a});return i.results.length>0?(k(i.results),{results:i.results,totalPages:i.totalPages}):(k([]),p("No exercises found for the selected category."),{results:[],totalPages:1})}catch(i){return p("Error fetching exercises"),console.error("Error fetching exercises:",i),{results:[],totalPages:1}}finally{D()}}function re({currentPage:n,totalPages:e,paginationContainer:t,updateExercises:s,currentBodypart:r,currentMuscles:a,currentEquipment:i,currentKeyword:l}){t.innerHTML="";let d,c;n===1?(d=1,c=Math.min(3,e)):n===e?(d=Math.max(1,e-2),c=e):(d=n-1,c=n+1);for(let o=d;o<=c;o++){const u=document.createElement("button");u.textContent=o,u.classList.add("pagination-btn"),o===n&&u.classList.add("pagination-current"),u.addEventListener("click",()=>{s({currentPage:o,currentBodypart:r,currentMuscles:a,currentEquipment:i,currentKeyword:l,paginationContainer:t,totalPages:e})}),t.appendChild(u)}}async function g({currentPage:n,currentBodypart:e,currentMuscles:t,currentEquipment:s,currentKeyword:r,paginationContainer:a,totalPages:i}){try{const l=await se({page:n,limit:8,bodypart:e||void 0,muscles:t||void 0,equipment:s||void 0,keyword:r||void 0});l&&l.totalPages&&(i=l.totalPages,re({currentPage:n,totalPages:i,paginationContainer:a,updateExercises:g,currentBodypart:e,currentMuscles:t,currentEquipment:s,currentKeyword:r}))}catch{p("Error fetching exercises")}}function oe(n,e,t,s,r,a,i,l){const d=n.target.closest("button");if(!d)return;const c=d.dataset.filter.toLowerCase(),o=d.dataset.name,u=document.querySelector(".filter-wrapper");u&&u.classList.add("hidden");const f=document.querySelector(".exercise-wrapper");f&&f.classList.remove("hidden"),document.querySelector(".main-title");const q=document.getElementById("selected-category"),x=document.getElementById("search-container");return c?x.classList.remove("hidden"):x.classList.add("hidden"),o?q.innerHTML=`
                <span class="category__slash"> / </span>
                <span class="category__selected">${o.charAt(0).toUpperCase()+o.slice(1).toLowerCase()}</span>
            `:q.innerHTML="",c==="bodypart"?(t=o,s="",r=""):c==="muscles"?(s=o,t="",r=""):c==="equipment"&&(r=o,t="",s=""),e=1,i({currentPage:e,currentBodypart:t,currentMuscles:s,currentEquipment:r,currentKeyword:a,paginationContainer:l,totalPages:1}),{currentPage:e,currentBodypart:t,currentMuscles:s,currentEquipment:r,currentKeyword:a}}function ae(n,e,t,s,r,a,i,l){n.preventDefault();const d=document.getElementById("search-input");return e=1,a=d.value.trim(),console.log("Filter applied:",{currentBodypart:t,currentMuscles:s,currentEquipment:r,currentKeyword:a}),i({currentPage:e,currentBodypart:t,currentMuscles:s,currentEquipment:r,currentKeyword:a,paginationContainer:l,totalPages:1}),{currentPage:e,currentBodypart:t,currentMuscles:s,currentEquipment:r,currentKeyword:a}}const ie=document.querySelector(".main-nav"),ce=document.querySelector(".pagination-section"),le=document.querySelector(".subscribe__form");window.addEventListener("resize",()=>{T(),A()});T();A();Z();ie.addEventListener("click",X);ce.addEventListener("click",K);le.addEventListener("submit",te);document.addEventListener("DOMContentLoaded",()=>{let n=1,e=1,t="",s="",r="",a="";document.getElementById("selected-category");const i=document.getElementById("search-form"),l=document.getElementById("pagination-container");document.querySelector(".filter-list").addEventListener("click",c=>{const o=oe(c,n,t,s,r,a,g,l);n=o.currentPage,t=o.currentBodypart,s=o.currentMuscles,r=o.currentEquipment,a=o.currentKeyword}),i.addEventListener("submit",c=>{const o=ae(c,n,t,s,r,a,g,l);n=o.currentPage,t=o.currentBodypart,s=o.currentMuscles,r=o.currentEquipment,a=o.currentKeyword}),document.querySelectorAll(".nav-btn").forEach(c=>{c.addEventListener("click",o=>{const u=document.querySelector(".exercise-wrapper");u&&u.classList.add("hidden");const f=document.querySelector(".filter-wrapper");f&&f.classList.remove("hidden")})}),document.querySelector(".main-nav").addEventListener("click",()=>{const c=document.getElementById("search-container");c&&c.classList.add("hidden");const o=document.getElementById("selected-category");o&&(o.innerHTML="")}),g({currentPage:n,currentBodypart:t,currentMuscles:s,currentEquipment:r,currentKeyword:a,paginationContainer:l,totalPages:e})});
//# sourceMappingURL=commonHelpers2.js.map
