import{r as y,F as p,o as L,t as m,f as h}from"./assets/filtersHandlers-cf0c2258.js";import"./assets/vendor-c65b4e60.js";const s=document.querySelector(".favorites-container-list"),l=e=>{const t=e.map(n=>y(n,!0)).join("");s.innerHTML=t},S=()=>{s.innerHTML=`
		<p class="favorites-container-empty">
			It appears that you haven't added any exercises to your favorites yet. 
			To get started, you can add exercises that you like to your favorites for easier access in the future.
		</p>
	`},u=document.querySelector(".pagination-section");function d(e){let t="";for(let n=1;n<=e;n++)t+=`
      <button type="button" class="pagination-btn untreated${n===1?" active":""}" data-page=${n}>${n}</button>
    `;u.innerHTML=t}function F(){u.innerHTML=""}function E(e){u.querySelectorAll(".pagination-btn").forEach(o=>o.classList.remove("active")),e.classList.add("active");const n=document.querySelector(".favorites-container-list");window.scrollTo({top:n.offsetTop,behavior:"smooth"})}const I=document.querySelector(".favorites-container-list");let i=[],a=1,r;function f(e=!0){i=JSON.parse(localStorage.getItem(p)),(i==null?void 0:i.length)>0?(window.innerWidth>=1440?(l(i),e&&F()):window.innerWidth<768?(r=8,l(v(a)),e&&d(Math.ceil(i.length/r))):(r=10,l(v(a)),e&&d(Math.ceil(i.length/r))),T()):S()}function g(){f(!1)}function T(){s.querySelectorAll(".start-btn").forEach(n=>{n.addEventListener("click",o=>{const c=o.target.dataset.id;L(c,g)})}),s.querySelectorAll("#deleteFavorite").forEach(n=>{n.addEventListener("click",o=>{const c=o.currentTarget.dataset.id;P(c)})})}function P(e){const t=i.findIndex(n=>n._id===e);t!==-1&&i.splice(t,1),localStorage.setItem(p,JSON.stringify(i)),g()}async function w(e){if(e.target.classList.contains("pagination-btn")){x();const t=e.target;a=t.dataset.page,g(),E(t)}}function x(e){I.innerHTML="",e&&(filterBtns.innerHTML="")}function v(e){let t=(e-1)*r;t>i.length-1&&(a=e=e-1,t=(a-1)*r,d(Math.ceil(i.length/r)));const n=t+r;return i.slice(t,n)}const M=document.querySelector(".pagination-section");M.addEventListener("click",w);window.addEventListener("resize",()=>{m(),f()});m();h();f();
//# sourceMappingURL=commonHelpers.js.map
