import{a as v,h as L,i as l}from"./assets/vendor-451007fb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function e(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=e(r);fetch(r.href,n)}})();const c=document.querySelector(".scrollup-btn"),S=function(){window.scrollY<300?c.classList.add("visually-hidden"):c.classList.remove("visually-hidden")};window.addEventListener("scroll",S);c.addEventListener("click",q);function q(){window.scrollTo({top:0,behavior:"smooth"})}const E=document.querySelector(".quote-text-wrapper"),h=document.querySelector(".filter-list"),u=document.querySelector(".pagination-section");function d(o){const t=o.results.map(e=>`
        <li class="filter-item">
          <button type="submit" class="filter-btn untreated data-filter=${e.filter} data-name=${e.name}">
            <div class="filter-container">
              <img class="filter-img" src="${e.imgURL}" alt="${e.name}" width=335 height=225>
              <div class="filter-overlay"></div>
              <p class="filter-name">${e.name}</p>
              <p class="filter-filter">${e.filter}</p>
            </div>  
          </button>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",t)}function F(o){let t="";for(let e=1;e<=o.totalPages;e++)t+=`
      <button type="button" class="pagination-btn untreated${e===1?" active":""}" data-page=${e}>${e}</button>
    `;u.insertAdjacentHTML("beforeend",t)}function g(o){const t=`
    <p class="quote-text">${o.quote}</p>
    <p class="quote-author">${o.author}</p>
  `;E.insertAdjacentHTML("beforeend",t)}function P(o){document.querySelectorAll(".nav-btn").forEach(e=>e.classList.remove("decorated")),o.target.classList.add("decorated")}function f(o){h.innerHTML="",o&&(u.innerHTML="")}function $(o){u.querySelectorAll(".pagination-btn").forEach(e=>e.classList.remove("active")),o.classList.add("active"),window.scrollTo(0,0)}const p=v.create({baseURL:"https://your-energy.b.goit.study/api/",timeout:3e3});async function m({page:o=1,limit:t=12,filter:e}){var s,r;try{return(await p.get("filters",{params:{page:o,limit:t,filter:e}})).data}catch(n){throw new Error(((r=(s=n.response)==null?void 0:s.data)==null?void 0:r.message)||n.message)}}async function M(){var o,t;try{return(await p.get("quote")).data}catch(e){throw new Error(((t=(o=e.response)==null?void 0:o.data)==null?void 0:t.message)||e.message)}}const i={filter:"Muscles",page:1,limit:null};async function T(o){P(o),f(!0),i.page=1,i.filter=o.target.dataset.filter;const t=await m(i);d(t),F(t)}async function B(){const o=L().format("L"),t=JSON.parse(localStorage.getItem("quote-data"));if(!t||t.date!==o){const e=await M();g(e);const s={};s.date=o,s.quote=e.quote,s.author=e.author,localStorage.clear("quote-data"),localStorage.setItem("quote-data",JSON.stringify(s))}else g(t)}async function w(){const o=window.innerWidth;let t=null;if(o>1439?t=12:t=9,t!==i.limit){f(!0),i.page=1,i.limit=t;const e=await m(i);d(e),F(e)}}async function C(o){f();const t=o.target;i.page=t.dataset.page;const e=await m(i);d(e),$(t)}async function O(o){var t,e;try{return(await p.post("subscription",{email:o})).data}catch(s){throw new Error(((e=(t=s.response)==null?void 0:t.data)==null?void 0:e.message)||s.message)}}l.settings({class:"custom-toast",position:"topRight",maxWidth:432,color:"#FFFFFF",titleColor:"#FFFFFF",messageColor:"#FFFFFF",iconColor:"#FFFFFF",displayMode:1});function N(o){l.info({message:o,backgroundColor:"#6C8CFF"})}function A(o){l.error({message:o,backgroundColor:"#EF4040"})}const b=document.querySelector(".subscribe__form"),y=b.querySelector('[name="email"]');async function H(o){if(o.preventDefault(),!!y.value)try{const t=y.value,e=await O(t);N(e.message),b.reset()}catch(t){A(t.message)}}const D=document.querySelector(".main-nav"),I=document.querySelector(".pagination-section"),j=document.querySelector(".subscribe__form");window.addEventListener("resize",()=>{w()});w();B();D.addEventListener("click",T);I.addEventListener("click",C);j.addEventListener("submit",H);
//# sourceMappingURL=commonHelpers.js.map
